---
- hosts: localhost
  vars:
    db_user: lcbo
    db_name: lcbo
    db_password: Secret5555
  tasks:
  - name: Install psql client
    become: true
    apt: name={{ item }} update_cache=true state=latest
    with_items:
    - postgresql-client
  - name: Install psycopg2 python package
    ansible.builtin.pip:
      name: psycopg2
  - name: deploy Docker Compose stack 
    community.docker.docker_compose_v2:
      project_src: '.'
      files:
      - docker-compose.yml
      state: present      
  - name: Create the database specified in vars
    postgresql_db: name={{ db_name }}
      login_host='localhost'
      login_user='devtedsuser'
      login_password='devtedspass'
      template='template0'
      state=present
  - name: Ensure user has access to the new database
    postgresql_user: login_db={{ db_name }}
      login_host='localhost'
      login_user='devtedsuser'
      login_password='devtedspass'
      name={{ db_user }}
      password={{ db_password }}
      state=present
  - name: Ensure user does not have unnecessary permissions
    postgresql_user: login_db={{ db_name }}
      name={{ db_user }}
      login_host='localhost'
      login_user='devtedsuser'
      login_password='devtedspass'
      role_attr_flags=NOSUPERUSER,NOCREATEDB
      state=present
  - name: Download lcbo database
    shell: "curl -o /tmp/lcboapi.tgz https://heycarsten.s3.amazonaws.com/lcboapi-2019-01-21.tgz && tar -zxvf /tmp/lcboapi.tgz --directory /tmp"
  - name: clean tsearch2
    shell: "grep -v tsearch2 /tmp/lcboapi-2019-01-21.sql> /tmp/lcboapi-clean.sql"
  - name: Restore dump
    postgresql_db: name={{ db_name }}
      login_host='localhost'
      login_user={{ db_user }}
      login_password={{ db_password }}
      template='template0'
      state='restore'
      target='/tmp/lcboapi-clean.sql'
